export const initialProgramStoreData = {
  id: 1797,
  trainerid: 10,
  traineruid: 100,
  athleteid: 162,
  userid: 169,
  name: "Big Man",
  description: "Try to get as massive as possible",
  sport: "Lifting",
  goal: "Get massive",
  status: 1,
  cycles: 5,
  currentcycle: 1,
  cycledays: 7,
  deloadcycles: 0,
  cyclelist: [
    {
      id: 4652,
      cycleno: 1,
      startdate: 1712844000,
      days: 7,
      phase: 0,
      workouts: [
        {
          id: 16467,
          cycleday: 1,
          scheduled: false,
          started: 1712911617,
          ended: 1712911901,
          questions: ["50"],
          exercises: [
            {
              id: 2,
              exercisegroupid: 0,
              exercisegroupname: "",
              programexerciseid: 0,
              workoutexerciseid: 80705,
              exerciseclass: "wrs",
              origname: "High Bar Back Squat",
              name: "High Bar Back Squat",
              description:
                "Sit down as low as you feel comfortable  Do not allow yourself to tip forward on the way up ",
              videolink:
                "https://www.youtube.com/watch?v=cV1z6bMUxsE&list=PLPA3Kd5k3BPUXRv6xvkeXR89Ye68khfgi&index=13",
              intensity: 90,
              progid: 1,
              prog: "standard",
              phase: 0,
              settings: {
                userest: "false",
                step: 0.5,
                intensity: 90,
                progid: 1,
                prog: "standard",
                planned: {
                  reps: "5",
                  sets: "3",
                },
              },
              planned: {
                reps: "5",
                sets: "4",
                ease: "50",
                max: "58",
                reprange: "0",
                weightrange: "0",
                weight: "81",
              },
              actual: {
                ease: "50",
                weight: "50",
                reps: "5",
                sets: "4",
              },
              disregard: 0,
              touched: 1,
              notes: "",
              ability: 58,
              extrajson: "{}",
              groups: [
                {
                  type_id: 0,
                  type_name: "Movement",
                  group_id: 32,
                  group_name: "Squat",
                },
                {
                  type_id: 3,
                  type_name: "Muscle",
                  group_id: 104,
                  group_name: "Quads",
                },
              ],
            },
            {
              id: 83,
              exercisegroupid: 0,
              exercisegroupname: "",
              programexerciseid: 0,
              workoutexerciseid: 80706,
              exerciseclass: "wrs",
              origname: "Leg Press",
              name: "Leg press",
              description:
                "Adjust machine to allow for greatest Range of motion without causing lower back Rounding or discomfort",
              videolink: null,
              intensity: 90,
              progid: 0,
              prog: "standard",
              phase: 0,
              settings: {
                userest: "false",
                step: 0.5,
                intensity: 85,
                progid: 1,
                prog: "standard",
                planned: {
                  reps: "8",
                  sets: "3",
                },
              },
              planned: {
                reps: "5",
                sets: "4",
                ease: "50",
                max: "84",
                reprange: "0",
                weightrange: "0",
              },
              actual: {
                weight: "66",
                reps: "5",
                sets: "4",
                ease: "50",
              },
              disregard: 0,
              touched: 1,
              notes: "",
              ability: 84,
              extrajson: "{}",
              groups: [
                {
                  type_id: 0,
                  type_name: "Movement",
                  group_id: 32,
                  group_name: "Squat",
                },
                {
                  type_id: 3,
                  type_name: "Muscle",
                  group_id: 104,
                  group_name: "Quads",
                },
              ],
            },
            {
              id: 14,
              exercisegroupid: 0,
              exercisegroupname: "",
              programexerciseid: 0,
              workoutexerciseid: 80707,
              exerciseclass: "wrs",
              origname: "Dumbbell Lunges",
              name: "Dumbell Lunge",
              description:
                "Try to drive through your front foot to get out of the bottom of the lift rather than kicking off your back foot.",
              videolink: "https://www.youtube.com/watch?v=kqDOliJZ7nU&ab_channel=RAWBarbellClub",
              intensity: 90,
              progid: 1,
              prog: "standard",
              phase: 0,
              settings: {
                userest: "false",
                step: 0.5,
                intensity: 90,
                progid: 1,
                prog: "reps",
                planned: {
                  reps: "15",
                  sets: "3",
                },
              },
              planned: {
                reps: "5",
                sets: "4",
                ease: "50",
                max: "11",
                reprange: "0",
                weightrange: "0",
                weight: "81",
              },
              actual: {
                weight: "9",
                reps: "5",
                sets: "4",
                ease: "50",
              },
              disregard: 0,
              touched: 1,
              notes: "",
              ability: 11,
              extrajson: "{}",
              groups: [
                {
                  type_id: 0,
                  type_name: "Movement",
                  group_id: 37,
                  group_name: "Unilateral Lower",
                },
                {
                  type_id: 3,
                  type_name: "Muscle",
                  group_id: 99,
                  group_name: "Glutes",
                },
              ],
            },
          ],
        },
        {
          id: 16468,
          cycleday: 3,
          scheduled: 136800,
          started: false,
          ended: false,
          questions: null,
          exercises: [
            {
              id: 30,
              exercisegroupid: 0,
              exercisegroupname: "",
              programexerciseid: 0,
              workoutexerciseid: 80708,
              exerciseclass: "wrs",
              origname: "2-Arm Dumbbell Curl",
              name: "Dumbbell Bicep Curl",
              description:
                "Keep your elbows pinned to your sides and make sure you get the full stretch of the bicep at the bottom of the lift",
              videolink: null,
              intensity: 90,
              progid: 1,
              prog: "standard",
              phase: 0,
              settings: {
                userest: "false",
                step: 0.5,
                intensity: 90,
                progid: 1,
                prog: "reps",
                planned: {
                  reps: "15",
                  sets: "3",
                },
              },
              planned: {
                reps: "5",
                sets: 4,
                ease: "50",
                max: 12,
                reprange: "0",
                weightrange: "0",
                weight: "81",
              },
              actual: null,
              disregard: 0,
              touched: 0,
              notes: "",
              ability: 12,
              extrajson: "{}",
              groups: [
                {
                  type_id: 0,
                  type_name: "Movement",
                  group_id: 3,
                  group_name: "Bicep Curl",
                },
                {
                  type_id: 3,
                  type_name: "Muscle",
                  group_id: 93,
                  group_name: "Biceps",
                },
              ],
            },
            {
              id: 24,
              exercisegroupid: 0,
              exercisegroupname: "",
              programexerciseid: 0,
              workoutexerciseid: 80709,
              exerciseclass: "wrs",
              origname: "Front Raises",
              name: "Front Raise",
              description: "Control the movement throughout making sure the bar doesn't swing",
              videolink: null,
              intensity: 90,
              progid: 1,
              prog: "standard",
              phase: 0,
              settings: {
                userest: "false",
                step: 0.5,
                intensity: 90,
                progid: 1,
                prog: "reps",
                planned: {
                  reps: "15",
                  sets: "3",
                },
              },
              planned: {
                reps: "5",
                sets: 4,
                ease: "50",
                max: 8,
                reprange: "0",
                weightrange: "0",
                weight: "81",
              },
              actual: null,
              disregard: 0,
              touched: 0,
              notes: "",
              ability: 8,
              extrajson: "{}",
              groups: [
                {
                  type_id: 0,
                  type_name: "Movement",
                  group_id: 26,
                  group_name: "Shoulder Raise",
                },
                {
                  type_id: 3,
                  type_name: "Muscle",
                  group_id: 97,
                  group_name: "Front Delts",
                },
              ],
            },
            {
              id: 9,
              exercisegroupid: 0,
              exercisegroupname: "",
              programexerciseid: 0,
              workoutexerciseid: 80710,
              exerciseclass: "wrs",
              origname: "Lateral Raise",
              name: "Lateral Raise",
              description: "Have constatnt tension throughout the lift. Do not use momentum ",
              videolink: null,
              intensity: 90,
              progid: 1,
              prog: "standard",
              phase: 0,
              settings: {
                userest: "false",
                step: 0.5,
                intensity: 90,
                progid: 1,
                prog: "reps",
                planned: {
                  reps: "15",
                  sets: "3",
                },
              },
              planned: {
                reps: "5",
                sets: 4,
                ease: "50",
                max: 10,
                reprange: "0",
                weightrange: "0",
                weight: "81",
              },
              actual: null,
              disregard: 0,
              touched: 0,
              notes: "",
              ability: 10,
              extrajson: "{}",
              groups: [
                {
                  type_id: 0,
                  type_name: "Movement",
                  group_id: 28,
                  group_name: "Side Delt",
                },
                {
                  type_id: 3,
                  type_name: "Muscle",
                  group_id: 105,
                  group_name: "Shoulder",
                },
              ],
            },
            {
              id: 8,
              exercisegroupid: 0,
              exercisegroupname: "",
              programexerciseid: 0,
              workoutexerciseid: 80711,
              exerciseclass: "wrs",
              origname: "Lat Pulldown",
              name: "Lat Pulldown",
              description: "sdfsdfsdfsd\nf\nsdf\nsdfs",
              videolink: null,
              intensity: 90,
              progid: 1,
              prog: "standard",
              phase: 0,
              settings: {
                userest: "false",
                step: 0.5,
                intensity: 85,
                progid: 1,
                prog: "standard",
                planned: {
                  reps: "12",
                  sets: "3",
                },
              },
              planned: {
                reps: "5",
                sets: 4,
                ease: "50",
                max: null,
                reprange: "0",
                weightrange: "0",
                weight: "81",
              },
              actual: null,
              disregard: 0,
              touched: 0,
              notes: "",
              ability: 0,
              extrajson: "{}",
              groups: [
                {
                  type_id: 0,
                  type_name: "Movement",
                  group_id: 38,
                  group_name: "Vertical Pull",
                },
                {
                  type_id: 3,
                  type_name: "Muscle",
                  group_id: 92,
                  group_name: "Back",
                },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 4653,
      cycleno: 2,
      startdate: 1713708000,
      days: 7,
      phase: 0,
      workouts: [
        {
          id: 16470,
          cycleday: 1,
          scheduled: false,
          started: 1712844000,
          ended: 1712911901,
          questions: null,
          exercises: [
            {
              id: 2,
              exercisegroupid: 0,
              exercisegroupname: "",
              programexerciseid: 0,
              workoutexerciseid: 80713,
              exerciseclass: "wrs",
              origname: "High Bar Back Squat",
              name: "High Bar Back Squat",
              description:
                "Sit down as low as you feel comfortable  Do not allow yourself to tip forward on the way up ",
              videolink:
                "https://www.youtube.com/watch?v=cV1z6bMUxsE&list=PLPA3Kd5k3BPUXRv6xvkeXR89Ye68khfgi&index=13",
              intensity: 90,
              progid: 1,
              prog: "standard",
              phase: 0,
              settings: {
                userest: "false",
                step: 0.5,
                intensity: 90,
                progid: 1,
                prog: "standard",
                planned: {
                  reps: "5",
                  sets: "3",
                },
              },
              planned: {
                reps: 5,
                sets: 4,
                ease: "50",
                max: 62.75,
                reprange: "0",
                weightrange: "0",
                weight: "81",
              },
              actual: null,
              disregard: 0,
              touched: 0,
              notes: "",
              ability: 58,
              extrajson: "{}",
              groups: [
                {
                  type_id: 0,
                  type_name: "Movement",
                  group_id: 32,
                  group_name: "Squat",
                },
                {
                  type_id: 3,
                  type_name: "Muscle",
                  group_id: 104,
                  group_name: "Quads",
                },
              ],
            },
            {
              id: 83,
              exercisegroupid: 0,
              exercisegroupname: "",
              programexerciseid: 0,
              workoutexerciseid: 80714,
              exerciseclass: "wrs",
              origname: "Leg Press",
              name: "Leg press",
              description:
                "Adjust machine to allow for greatest Range of motion without causing lower back Rounding or discomfort",
              videolink: null,
              intensity: 90,
              progid: 0,
              prog: "standard",
              phase: 0,
              settings: {
                userest: "false",
                step: 0.5,
                intensity: 85,
                progid: 1,
                prog: "standard",
                planned: {
                  reps: "8",
                  sets: "3",
                },
              },
              planned: {
                reps: 5,
                sets: 4,
                ease: "50",
                max: 83,
                reprange: "0",
                weightrange: "0",
              },
              actual: null,
              disregard: 0,
              touched: 0,
              notes: "",
              ability: 84,
              extrajson: "{}",
              groups: [
                {
                  type_id: 0,
                  type_name: "Movement",
                  group_id: 32,
                  group_name: "Squat",
                },
                {
                  type_id: 3,
                  type_name: "Muscle",
                  group_id: 104,
                  group_name: "Quads",
                },
              ],
            },
            {
              id: 14,
              exercisegroupid: 0,
              exercisegroupname: "",
              programexerciseid: 0,
              workoutexerciseid: 80715,
              exerciseclass: "wrs",
              origname: "Dumbbell Lunges",
              name: "Dumbell Lunge",
              description:
                "Try to drive through your front foot to get out of the bottom of the lift rather than kicking off your back foot.",
              videolink: "https://www.youtube.com/watch?v=kqDOliJZ7nU&ab_channel=RAWBarbellClub",
              intensity: 90,
              progid: 1,
              prog: "standard",
              phase: 0,
              settings: {
                userest: "false",
                step: 0.5,
                intensity: 90,
                progid: 1,
                prog: "reps",
                planned: {
                  reps: "15",
                  sets: "3",
                },
              },
              planned: {
                reps: 5,
                sets: 4,
                ease: "50",
                max: 11.25,
                reprange: "0",
                weightrange: "0",
                weight: "81",
              },
              actual: null,
              disregard: 0,
              touched: 0,
              notes: "",
              ability: 11,
              extrajson: "{}",
              groups: [
                {
                  type_id: 0,
                  type_name: "Movement",
                  group_id: 37,
                  group_name: "Unilateral Lower",
                },
                {
                  type_id: 3,
                  type_name: "Muscle",
                  group_id: 99,
                  group_name: "Glutes",
                },
              ],
            },
          ],
        },
        {
          id: 16471,
          cycleday: 3,
          scheduled: 136800,
          started: false,
          ended: false,
          questions: null,
          exercises: [
            {
              id: 30,
              exercisegroupid: 0,
              exercisegroupname: "",
              programexerciseid: 0,
              workoutexerciseid: 80716,
              exerciseclass: "wrs",
              origname: "2-Arm Dumbbell Curl",
              name: "Dumbbell Bicep Curl",
              description:
                "Keep your elbows pinned to your sides and make sure you get the full stretch of the bicep at the bottom of the lift",
              videolink: null,
              intensity: 90,
              progid: 1,
              prog: "standard",
              phase: 0,
              settings: {
                userest: "false",
                step: 0.5,
                intensity: 90,
                progid: 1,
                prog: "reps",
                planned: {
                  reps: "15",
                  sets: "3",
                },
              },
              planned: {
                reps: "5",
                sets: 4,
                ease: "50",
                max: 12,
                reprange: "0",
                weightrange: "0",
                weight: "81",
              },
              actual: null,
              disregard: 0,
              touched: 0,
              notes: "",
              ability: 12,
              extrajson: "{}",
              groups: [
                {
                  type_id: 0,
                  type_name: "Movement",
                  group_id: 3,
                  group_name: "Bicep Curl",
                },
                {
                  type_id: 3,
                  type_name: "Muscle",
                  group_id: 93,
                  group_name: "Biceps",
                },
              ],
            },
            {
              id: 24,
              exercisegroupid: 0,
              exercisegroupname: "",
              programexerciseid: 0,
              workoutexerciseid: 80717,
              exerciseclass: "wrs",
              origname: "Front Raises",
              name: "Front Raise",
              description: "Control the movement throughout making sure the bar doesn't swing",
              videolink: null,
              intensity: 90,
              progid: 1,
              prog: "standard",
              phase: 0,
              settings: {
                userest: "false",
                step: 0.5,
                intensity: 90,
                progid: 1,
                prog: "reps",
                planned: {
                  reps: "15",
                  sets: "3",
                },
              },
              planned: {
                reps: "5",
                sets: 4,
                ease: "50",
                max: 8,
                reprange: "0",
                weightrange: "0",
                weight: "81",
              },
              actual: null,
              disregard: 0,
              touched: 0,
              notes: "",
              ability: 8,
              extrajson: "{}",
              groups: [
                {
                  type_id: 0,
                  type_name: "Movement",
                  group_id: 26,
                  group_name: "Shoulder Raise",
                },
                {
                  type_id: 3,
                  type_name: "Muscle",
                  group_id: 97,
                  group_name: "Front Delts",
                },
              ],
            },
            {
              id: 9,
              exercisegroupid: 0,
              exercisegroupname: "",
              programexerciseid: 0,
              workoutexerciseid: 80718,
              exerciseclass: "wrs",
              origname: "Lateral Raise",
              name: "Lateral Raise",
              description: "Have constatnt tension throughout the lift. Do not use momentum ",
              videolink: null,
              intensity: 90,
              progid: 1,
              prog: "standard",
              phase: 0,
              settings: {
                userest: "false",
                step: 0.5,
                intensity: 90,
                progid: 1,
                prog: "reps",
                planned: {
                  reps: "15",
                  sets: "3",
                },
              },
              planned: {
                reps: "5",
                sets: 4,
                ease: "50",
                max: 10,
                reprange: "0",
                weightrange: "0",
                weight: "81",
              },
              actual: null,
              disregard: 0,
              touched: 0,
              notes: "",
              ability: 10,
              extrajson: "{}",
              groups: [
                {
                  type_id: 0,
                  type_name: "Movement",
                  group_id: 28,
                  group_name: "Side Delt",
                },
                {
                  type_id: 3,
                  type_name: "Muscle",
                  group_id: 105,
                  group_name: "Shoulder",
                },
              ],
            },
            {
              id: 8,
              exercisegroupid: 0,
              exercisegroupname: "",
              programexerciseid: 0,
              workoutexerciseid: 80719,
              exerciseclass: "wrs",
              origname: "Lat Pulldown",
              name: "Lat Pulldown",
              description: "sdfsdfsdfsd\nf\nsdf\nsdfs",
              videolink: null,
              intensity: 90,
              progid: 1,
              prog: "standard",
              phase: 0,
              settings: {
                userest: "false",
                step: 0.5,
                intensity: 85,
                progid: 1,
                prog: "standard",
                planned: {
                  reps: "12",
                  sets: "3",
                },
              },
              planned: {
                reps: "5",
                sets: 4,
                ease: "50",
                max: null,
                reprange: "0",
                weightrange: "0",
                weight: "81",
              },
              actual: null,
              disregard: 0,
              touched: 0,
              notes: "",
              ability: 0,
              extrajson: "{}",
              groups: [
                {
                  type_id: 0,
                  type_name: "Movement",
                  group_id: 38,
                  group_name: "Vertical Pull",
                },
                {
                  type_id: 3,
                  type_name: "Muscle",
                  group_id: 92,
                  group_name: "Back",
                },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 4654,
      cycleno: 3,
      startdate: 1713708000,
      days: 7,
      phase: 0,
      workouts: [
        {
          id: 16472,
          cycleday: 1,
          scheduled: false,
          started: 1712844000,
          ended: 1712911901,
          questions: null,
          exercises: [
            {
              id: 2,
              exercisegroupid: 0,
              exercisegroupname: "",
              programexerciseid: 0,
              workoutexerciseid: 80720,
              exerciseclass: "wrs",
              origname: "High Bar Back Squat",
              name: "High Bar Back Squat",
              description:
                "Sit down as low as you feel comfortable  Do not allow yourself to tip forward on the way up ",
              videolink:
                "https://www.youtube.com/watch?v=cV1z6bMUxsE&list=PLPA3Kd5k3BPUXRv6xvkeXR89Ye68khfgi&index=13",
              intensity: 90,
              progid: 1,
              prog: "standard",
              phase: 0,
              settings: {
                userest: "false",
                step: 0.5,
                intensity: 90,
                progid: 1,
                prog: "standard",
                planned: {
                  reps: "5",
                  sets: "3",
                },
              },
              planned: {
                reps: 5,
                sets: 4,
                ease: "50",
                max: 62.75,
                reprange: "0",
                weightrange: "0",
                weight: "81",
              },
              actual: null,
              disregard: 0,
              touched: 0,
              notes: "",
              ability: 58,
              extrajson: "{}",
              groups: [
                {
                  type_id: 0,
                  type_name: "Movement",
                  group_id: 32,
                  group_name: "Squat",
                },
                {
                  type_id: 3,
                  type_name: "Muscle",
                  group_id: 104,
                  group_name: "Quads",
                },
              ],
            },
            {
              id: 83,
              exercisegroupid: 0,
              exercisegroupname: "",
              programexerciseid: 0,
              workoutexerciseid: 80721,
              exerciseclass: "wrs",
              origname: "Leg Press",
              name: "Leg press",
              description:
                "Adjust machine to allow for greatest Range of motion without causing lower back Rounding or discomfort",
              videolink: null,
              intensity: 90,
              progid: 0,
              prog: "standard",
              phase: 0,
              settings: {
                userest: "false",
                step: 0.5,
                intensity: 85,
                progid: 1,
                prog: "standard",
                planned: {
                  reps: "8",
                  sets: "3",
                },
              },
              planned: {
                reps: 5,
                sets: 4,
                ease: "50",
                max: 83,
                reprange: "0",
                weightrange: "0",
                weight: null,
              },
              actual: null,
              disregard: 0,
              touched: 0,
              notes: "",
              ability: 84,
              extrajson: "{}",
              groups: [
                {
                  type_id: 0,
                  type_name: "Movement",
                  group_id: 32,
                  group_name: "Squat",
                },
                {
                  type_id: 3,
                  type_name: "Muscle",
                  group_id: 104,
                  group_name: "Quads",
                },
              ],
            },
            {
              id: 14,
              exercisegroupid: 0,
              exercisegroupname: "",
              programexerciseid: 0,
              workoutexerciseid: 80722,
              exerciseclass: "wrs",
              origname: "Dumbbell Lunges",
              name: "Dumbell Lunge",
              description:
                "Try to drive through your front foot to get out of the bottom of the lift rather than kicking off your back foot.",
              videolink: "https://www.youtube.com/watch?v=kqDOliJZ7nU&ab_channel=RAWBarbellClub",
              intensity: 90,
              progid: 1,
              prog: "standard",
              phase: 0,
              settings: {
                userest: "false",
                step: 0.5,
                intensity: 90,
                progid: 1,
                prog: "reps",
                planned: {
                  reps: "15",
                  sets: "3",
                },
              },
              planned: {
                reps: 5,
                sets: 4,
                ease: "50",
                max: 11.25,
                reprange: "0",
                weightrange: "0",
                weight: "81",
              },
              actual: null,
              disregard: 0,
              touched: 0,
              notes: "",
              ability: 11,
              extrajson: "{}",
              groups: [
                {
                  type_id: 0,
                  type_name: "Movement",
                  group_id: 37,
                  group_name: "Unilateral Lower",
                },
                {
                  type_id: 3,
                  type_name: "Muscle",
                  group_id: 99,
                  group_name: "Glutes",
                },
              ],
            },
          ],
        },
        {
          id: 16473,
          cycleday: 3,
          scheduled: 136800,
          started: false,
          ended: false,
          questions: null,
          exercises: [
            {
              id: 30,
              exercisegroupid: 0,
              exercisegroupname: "",
              programexerciseid: 0,
              workoutexerciseid: 80723,
              exerciseclass: "wrs",
              origname: "2-Arm Dumbbell Curl",
              name: "Dumbbell Bicep Curl",
              description:
                "Keep your elbows pinned to your sides and make sure you get the full stretch of the bicep at the bottom of the lift",
              videolink: null,
              intensity: 90,
              progid: 1,
              prog: "standard",
              phase: 0,
              settings: {
                userest: "false",
                step: 0.5,
                intensity: 90,
                progid: 1,
                prog: "reps",
                planned: {
                  reps: "15",
                  sets: "3",
                },
              },
              planned: {
                reps: "5",
                sets: 4,
                ease: "50",
                max: 12,
                reprange: "0",
                weightrange: "0",
                weight: "81",
              },
              actual: null,
              disregard: 0,
              touched: 0,
              notes: "",
              ability: 12,
              extrajson: "{}",
              groups: [
                {
                  type_id: 0,
                  type_name: "Movement",
                  group_id: 3,
                  group_name: "Bicep Curl",
                },
                {
                  type_id: 3,
                  type_name: "Muscle",
                  group_id: 93,
                  group_name: "Biceps",
                },
              ],
            },
            {
              id: 24,
              exercisegroupid: 0,
              exercisegroupname: "",
              programexerciseid: 0,
              workoutexerciseid: 80724,
              exerciseclass: "wrs",
              origname: "Front Raises",
              name: "Front Raise",
              description: "Control the movement throughout making sure the bar doesn't swing",
              videolink: null,
              intensity: 90,
              progid: 1,
              prog: "standard",
              phase: 0,
              settings: {
                userest: "false",
                step: 0.5,
                intensity: 90,
                progid: 1,
                prog: "reps",
                planned: {
                  reps: "15",
                  sets: "3",
                },
              },
              planned: {
                reps: "5",
                sets: 4,
                ease: "50",
                max: 8,
                reprange: "0",
                weightrange: "0",
                weight: "81",
              },
              actual: null,
              disregard: 0,
              touched: 0,
              notes: "",
              ability: 8,
              extrajson: "{}",
              groups: [
                {
                  type_id: 0,
                  type_name: "Movement",
                  group_id: 26,
                  group_name: "Shoulder Raise",
                },
                {
                  type_id: 3,
                  type_name: "Muscle",
                  group_id: 97,
                  group_name: "Front Delts",
                },
              ],
            },
            {
              id: 9,
              exercisegroupid: 0,
              exercisegroupname: "",
              programexerciseid: 0,
              workoutexerciseid: 80725,
              exerciseclass: "wrs",
              origname: "Lateral Raise",
              name: "Lateral Raise",
              description: "Have constatnt tension throughout the lift. Do not use momentum ",
              videolink: null,
              intensity: 90,
              progid: 1,
              prog: "standard",
              phase: 0,
              settings: {
                userest: "false",
                step: 0.5,
                intensity: 90,
                progid: 1,
                prog: "reps",
                planned: {
                  reps: "15",
                  sets: "3",
                },
              },
              planned: {
                reps: "5",
                sets: 4,
                ease: "50",
                max: 10,
                reprange: "0",
                weightrange: "0",
                weight: "81",
              },
              actual: null,
              disregard: 0,
              touched: 0,
              notes: "",
              ability: 10,
              extrajson: "{}",
              groups: [
                {
                  type_id: 0,
                  type_name: "Movement",
                  group_id: 28,
                  group_name: "Side Delt",
                },
                {
                  type_id: 3,
                  type_name: "Muscle",
                  group_id: 105,
                  group_name: "Shoulder",
                },
              ],
            },
            {
              id: 8,
              exercisegroupid: 0,
              exercisegroupname: "",
              programexerciseid: 0,
              workoutexerciseid: 80726,
              exerciseclass: "wrs",
              origname: "Lat Pulldown",
              name: "Lat Pulldown",
              description: "sdfsdfsdfsd\nf\nsdf\nsdfs",
              videolink: null,
              intensity: 90,
              progid: 1,
              prog: "standard",
              phase: 0,
              settings: {
                userest: "false",
                step: 0.5,
                intensity: 85,
                progid: 1,
                prog: "standard",
                planned: {
                  reps: "12",
                  sets: "3",
                },
              },
              planned: {
                reps: "5",
                sets: 4,
                ease: "50",
                max: null,
                reprange: "0",
                weightrange: "0",
                weight: "81",
              },
              actual: null,
              disregard: 0,
              touched: 0,
              notes: "",
              ability: 0,
              extrajson: "{}",
              groups: [
                {
                  type_id: 0,
                  type_name: "Movement",
                  group_id: 38,
                  group_name: "Vertical Pull",
                },
                {
                  type_id: 3,
                  type_name: "Muscle",
                  group_id: 92,
                  group_name: "Back",
                },
              ],
            },
          ],
        },
      ],
    },
  ],
}
